export '../../../flutter_flow/lat_lng.dart';
export 'package:supabase_flutter/supabase_flutter.dart' hide Provider;

export '../supabase.dart';
export 'row.dart';
export 'table.dart';

export 'tables/vendas_equipes.dart';
export 'tables/producoes_codigo_produtos.dart';
export 'tables/producoesv2.dart';
export 'tables/locais.dart';
export 'tables/grupos_convenios.dart';
export 'tables/tipos_locais.dart';
export 'tables/campanhas_historicos.dart';
export 'tables/clientes.dart';
export 'tables/comissoes.dart';
export 'tables/estados.dart';
export 'tables/remuneracoes.dart';
export 'tables/meta_bb.dart';
export 'tables/notificacoes.dart';
export 'tables/calendario_pagamentos.dart';
export 'tables/producoes_historicos.dart';
export 'tables/producoes_codigo_convenios.dart';
export 'tables/equipes.dart';
export 'tables/cargos.dart';
export 'tables/comissoes_gerentes.dart';
export 'tables/pagamentos.dart';
export 'tables/grupos_produtos.dart';
export 'tables/usuarios.dart';
export 'tables/cidades.dart';
export 'tables/historico_clientes.dart';
export 'tables/campanha_leads.dart';
export 'tables/simulacoes.dart';
export 'tables/promovida_contatos.dart';
export 'tables/metas_agentes.dart';
export 'tables/agencias.dart';
